n = input("write something: ")
print(type(n))
print("É alfanumérico? ", n.isalnum())
print("É do alfabeto? ", n.isalpha())
print("É numérico? ", n.isnumeric())
print("Fazem parte da tabela ascii? ", n.isascii())
print("É digito? ", n.isdigit())
print("É decimal? ", n.isdecimal())
print("É identificador? ", n.isidentifier())
print("Pode ser printado? ", n.isprintable())
print("É um espaço? ", n.isspace())
print("É um título?? ", n.istitle())
print("Esta em letra maiúscula? ", n.isupper())
print("Esta em letra minúscula? ", n.islower())
